import React from 'react'
import ReactDOM from 'react-dom/client'
import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import App from './App'
import './index.css'

const storedLang = (() => {
  const s = localStorage.getItem('miage-lang')
  return s === 'fr' || s === 'en' || s === 'ar' ? s : 'fr'
})()

i18n.use(initReactI18next).init({
  lng: storedLang,
  fallbackLng: 'fr',
  interpolation: { escapeValue: false },
  resources: {
    fr: {
      translation: {
        appName: 'MIAGE Calculator',
        semester: 'Semestre',
        s1: 'S1', s2: 'S2', s3: 'S3', s4: 'S4', s5: 'S5', s6: 'S6',
        l1: 'L1', l2: 'L2', l3: 'L3',
        licence: 'Licence',
        exam: 'Examen', td: 'TD', tp: 'TP',
        validated: 'VALIDÉ',
        notValidated: 'NON VALIDÉ',
        semesterValidated: 'SEMESTRE VALIDÉ',
        semesterNotValidated: 'SEMESTRE NON VALIDÉ',
        yearValidated: 'ANNÉE VALIDÉE',
        yearNotValidated: 'ANNÉE NON VALIDÉE',
        licenceValidated: 'LICENCE VALIDÉE',
        licenceNotValidated: 'LICENCE NON VALIDÉE',
        average: 'Moyenne',
        credits: 'Crédits',
        creditsEarned: 'Crédits validés',
        totalCredits: 'Total crédits',
        coefficient: 'Coeff.',
        course: 'Matière',
        grade: 'Note',
        status: 'Statut',
        reset: 'Réinitialiser',
        resetAll: 'Tout réinitialiser',
        resetConfirm: 'Réinitialiser ce semestre ?',
        resetAllConfirm: 'Réinitialiser toutes les notes ?',
        simulatorTitle: 'Simulateur de notes',
        simulatorQuestion: "De quelle note ai-je besoin pour valider ?",
        neededScore: "Note d'examen requise",
        impossible: 'Impossible (> 20)',
        alreadyPassed: 'Déjà validé (TD/TP)',
        noGrades: 'Aucune note saisie pour ce semestre',
        selectCourse: 'Choisir une matière...',
        enterTd: 'Note TD',
        enterTp: 'Note TP',
        customPerc: 'Personnaliser',
        percSum: 'La somme doit être 100 %',
        apply: 'Appliquer',
        cancel: 'Annuler',
        l1Avg: 'Moyenne L1',
        l2Avg: 'Moyenne L2',
        l3Avg: 'Moyenne L3',
        licenceAvg: 'Moyenne Licence',
        yearAvg: 'Moyenne annuelle',
        semSummary: 'Bilan du semestre',
        licenceSummary: 'Bilan Licence',
        darkMode: 'Mode sombre',
        lightMode: 'Mode clair',
        editPerc: 'Modifier les %',
        helpBtn: 'Aide',
        semAvgLabel: 'Moyenne',
        enterSemAvg: 'Entrez la moyenne...',
        manualNote: 'Saisissez les moyennes de vos semestres ci-dessous',
        devBy: 'Développé par A-CH',
      },
    },
    en: {
      translation: {
        appName: 'MIAGE Calculator',
        semester: 'Semester',
        s1: 'S1', s2: 'S2', s3: 'S3', s4: 'S4', s5: 'S5', s6: 'S6',
        l1: 'L1', l2: 'L2', l3: 'L3',
        licence: 'Degree',
        exam: 'Exam', td: 'Tutorial', tp: 'Lab',
        validated: 'PASSED',
        notValidated: 'FAILED',
        semesterValidated: 'SEMESTER PASSED',
        semesterNotValidated: 'SEMESTER FAILED',
        yearValidated: 'YEAR PASSED',
        yearNotValidated: 'YEAR FAILED',
        licenceValidated: 'DEGREE PASSED',
        licenceNotValidated: 'DEGREE FAILED',
        average: 'Average',
        credits: 'Credits',
        creditsEarned: 'Credits earned',
        totalCredits: 'Total credits',
        coefficient: 'Coeff.',
        course: 'Course',
        grade: 'Grade',
        status: 'Status',
        reset: 'Reset',
        resetAll: 'Reset all',
        resetConfirm: 'Reset this semester?',
        resetAllConfirm: 'Reset all grades?',
        simulatorTitle: 'Grade Simulator',
        simulatorQuestion: 'What exam score do I need to pass?',
        neededScore: 'Required exam score',
        impossible: 'Impossible (> 20)',
        alreadyPassed: 'Already passing (TD/TP)',
        noGrades: 'No grades entered for this semester',
        selectCourse: 'Select a course...',
        enterTd: 'Tutorial grade',
        enterTp: 'Lab grade',
        customPerc: 'Customize',
        percSum: 'Must sum to 100 %',
        apply: 'Apply',
        cancel: 'Cancel',
        l1Avg: 'L1 Average',
        l2Avg: 'L2 Average',
        l3Avg: 'L3 Average',
        licenceAvg: 'Degree Average',
        yearAvg: 'Year average',
        semSummary: 'Semester summary',
        licenceSummary: 'Degree summary',
        darkMode: 'Dark mode',
        lightMode: 'Light mode',
        editPerc: 'Edit %',
        helpBtn: 'Help',
        semAvgLabel: 'Average',
        enterSemAvg: 'Enter average...',
        manualNote: 'Enter your semester averages below',
        devBy: 'Developed by A-CH',
      },
    },
    ar: {
      translation: {
        appName: 'حاسبة MIAGE',
        semester: 'الفصل',
        s1: 'ف1', s2: 'ف2', s3: 'ف3', s4: 'ف4', s5: 'ف5', s6: 'ف6',
        l1: 'س1', l2: 'س2', l3: 'س3',
        licence: 'الليسانس',
        exam: 'الامتحان', td: 'أ.م', tp: 'أ.ت',
        validated: 'ناجح',
        notValidated: 'راسب',
        semesterValidated: 'الفصل ناجح',
        semesterNotValidated: 'الفصل راسب',
        yearValidated: 'السنة ناجحة',
        yearNotValidated: 'السنة راسبة',
        licenceValidated: 'الليسانس ناجح',
        licenceNotValidated: 'الليسانس راسب',
        average: 'المعدل',
        credits: 'الرصيد',
        creditsEarned: 'الرصيد المكتسب',
        totalCredits: 'مجموع الرصيد',
        coefficient: 'المعامل',
        course: 'المادة',
        grade: 'الدرجة',
        status: 'الحالة',
        reset: 'إعادة تعيين',
        resetAll: 'إعادة تعيين الكل',
        resetConfirm: 'إعادة تعيين هذا الفصل ؟',
        resetAllConfirm: 'إعادة تعيين جميع الدرجات ؟',
        simulatorTitle: 'محاكي الدرجات',
        simulatorQuestion: 'ما درجة الامتحان التي أحتاجها للنجاح ؟',
        neededScore: 'درجة الامتحان المطلوبة',
        impossible: 'مستحيل (> 20)',
        alreadyPassed: 'ناجح بالأعمال الموجهة/التطبيقية',
        noGrades: 'لم تُدخل درجات لهذا الفصل',
        selectCourse: 'اختر مادة...',
        enterTd: 'درجة الأعمال الموجهة',
        enterTp: 'درجة الأعمال التطبيقية',
        customPerc: 'تخصيص',
        percSum: 'يجب أن يكون المجموع 100 %',
        apply: 'تطبيق',
        cancel: 'إلغاء',
        l1Avg: 'معدل السنة الأولى',
        l2Avg: 'معدل السنة الثانية',
        l3Avg: 'معدل السنة الثالثة',
        licenceAvg: 'معدل الليسانس',
        yearAvg: 'معدل السنة',
        semSummary: 'ملخص الفصل',
        licenceSummary: 'ملخص الليسانس',
        darkMode: 'الوضع الداكن',
        lightMode: 'الوضع الفاتح',
        editPerc: 'تعديل النسب',
        helpBtn: 'مساعدة',
        semAvgLabel: 'المعدل',
        enterSemAvg: 'أدخل المعدل...',
        manualNote: 'أدخل معدلات فصولك أدناه',
        devBy: 'طُوِّر بواسطة A-CH',
      },
    },
  },
})

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
